// Message type: envoy.config.core.v3.HealthCheck.Payload
// Definition generated by protoc-gen-jsonnet. DO NOT EDIT.

local type = 'envoy.config.core.v3.HealthCheck.Payload';
local generator = import '../generator.libsonnet';
local fields = {
  binary: {
    type: 'bytes',
    allowedNames: [
      'binary',
    ],
  },
  text: {
    type: 'string',
    allowedNames: [
      'text',
    ],
    constraints: {
      String_: {
        WellKnown: null,
        min_len: 1,
      },
    },
  },
};
local oneOfs = [
  {
    fields: [
      'text',
      'binary',
    ],
    required: true,
    group: 'payload',
  },
];
local validator = generator(type, fields, oneOfs);

{
  definition: {

    // methods
    _new:: function(partialObject={}) (
      local obj = if std.type(partialObject) != 'object' then error 'expected object for _new invocation of %s' % type else partialObject;
      validator.validatePartial(obj + self)
    ),
    _validate:: function() validator.validateAll(self),
    _normalize:: function(kind='') validator.normalizeAll(self, kind),
    withBinary:: function(val) validator.validateField(self + { binary: val }, 'binary', type + '.withBinary'),
    withText:: function(val) validator.validateField(self + { text: val }, 'text', type + '.withText'),
  },
  validator:: validator.validateAll,
  normalizer: validator.normalizeAll,
}
