// Message type: validate.BoolRules
// Definition generated by protoc-gen-jsonnet. DO NOT EDIT.

local type = 'validate.BoolRules';
local generator = import '../generator.libsonnet';
local fields = {
  const: {
    type: 'bool',
    allowedNames: [
      'const',
    ],
  },
};
local oneOfs = [];
local validator = generator(type, fields, oneOfs);

{
  definition: {

    // methods
    _new:: function(partialObject={}) (
      local obj = if std.type(partialObject) != 'object' then error 'expected object for _new invocation of %s' % type else partialObject;
      validator.validatePartial(obj + self)
    ),
    _validate:: function() validator.validateAll(self),
    _normalize:: function(kind='') validator.normalizeAll(self, kind),
    withConst:: function(val) validator.validateField(self + { const: val }, 'const', type + '.withConst'),
  },
  validator:: validator.validateAll,
  normalizer: validator.normalizeAll,
}
