// Enum type: validate.KnownRegex
// Definition generated by protoc-gen-jsonnet. DO NOT EDIT.
local type = 'validate.KnownRegex';
local map = {
  HTTP_HEADER_NAME: 'HTTP_HEADER_NAME',
  HTTP_HEADER_VALUE: 'HTTP_HEADER_VALUE',
  UNKNOWN: 'UNKNOWN',
};

local reverseMap = {
  '0': 'UNKNOWN',
  '1': 'HTTP_HEADER_NAME',
  '2': 'HTTP_HEADER_VALUE',
};

local validator = function(input, ctx='') (
  local context = if ctx == '' then type else ctx;
  local v = std.toString(input);
  if std.objectHas(map, v) || std.objectHas(reverseMap, v)
  then input
  else error '%s: invalid value %s for enum %s' % [context, v, type]
);

{
  definition: map {
    _new:: function(obj={}) error '%s: the _new method may not be used on enum types' % 'validate.KnownRegex',
    _validate:: validator,
  },
  validator:: validator,
}
