// Message type: validate.MessageRules
// Definition generated by protoc-gen-jsonnet. DO NOT EDIT.

local type = 'validate.MessageRules';
local generator = import '../generator.libsonnet';
local fields = {
  required: {
    type: 'bool',
    allowedNames: [
      'required',
    ],
  },
  skip: {
    type: 'bool',
    allowedNames: [
      'skip',
    ],
  },
};
local oneOfs = [];
local validator = generator(type, fields, oneOfs);

{
  definition: {

    // methods
    _new:: function(partialObject={}) (
      local obj = if std.type(partialObject) != 'object' then error 'expected object for _new invocation of %s' % type else partialObject;
      validator.validatePartial(obj + self)
    ),
    _validate:: function() validator.validateAll(self),
    _normalize:: function(kind='') validator.normalizeAll(self, kind),
    withRequired:: function(val) validator.validateField(self + { required: val }, 'required', type + '.withRequired'),
    withSkip:: function(val) validator.validateField(self + { skip: val }, 'skip', type + '.withSkip'),
  },
  validator:: validator.validateAll,
  normalizer: validator.normalizeAll,
}
