// Message type: validate.TimestampRules
// Definition generated by protoc-gen-jsonnet. DO NOT EDIT.

local type = 'validate.TimestampRules';
local generator = import '../generator.libsonnet';
local fields = {
  const: {
    type: 'google.protobuf.Timestamp',
    allowedNames: [
      'const',
    ],
  },
  gt: {
    type: 'google.protobuf.Timestamp',
    allowedNames: [
      'gt',
    ],
  },
  gt_now: {
    type: 'bool',
    allowedNames: [
      'gt_now',
      'gtNow',
    ],
  },
  gte: {
    type: 'google.protobuf.Timestamp',
    allowedNames: [
      'gte',
    ],
  },
  lt: {
    type: 'google.protobuf.Timestamp',
    allowedNames: [
      'lt',
    ],
  },
  lt_now: {
    type: 'bool',
    allowedNames: [
      'lt_now',
      'ltNow',
    ],
  },
  lte: {
    type: 'google.protobuf.Timestamp',
    allowedNames: [
      'lte',
    ],
  },
  required: {
    type: 'bool',
    allowedNames: [
      'required',
    ],
  },
  within: {
    type: 'google.protobuf.Duration',
    allowedNames: [
      'within',
    ],
  },
};
local oneOfs = [];
local validator = generator(type, fields, oneOfs);

{
  definition: {

    // methods
    _new:: function(partialObject={}) (
      local obj = if std.type(partialObject) != 'object' then error 'expected object for _new invocation of %s' % type else partialObject;
      validator.validatePartial(obj + self)
    ),
    _validate:: function() validator.validateAll(self),
    _normalize:: function(kind='') validator.normalizeAll(self, kind),
    withConst:: function(val) validator.validateField(self + { const: val }, 'const', type + '.withConst'),
    withGt:: function(val) validator.validateField(self + { gt: val }, 'gt', type + '.withGt'),
    withGtNow:: function(val) validator.validateField(self + { gt_now: val }, 'gt_now', type + '.withGtNow'),
    withGte:: function(val) validator.validateField(self + { gte: val }, 'gte', type + '.withGte'),
    withLt:: function(val) validator.validateField(self + { lt: val }, 'lt', type + '.withLt'),
    withLtNow:: function(val) validator.validateField(self + { lt_now: val }, 'lt_now', type + '.withLtNow'),
    withLte:: function(val) validator.validateField(self + { lte: val }, 'lte', type + '.withLte'),
    withRequired:: function(val) validator.validateField(self + { required: val }, 'required', type + '.withRequired'),
    withWithin:: function(val) validator.validateField(self + { within: val }, 'within', type + '.withWithin'),
  },
  validator:: validator.validateAll,
  normalizer: validator.normalizeAll,
}
